### ISSUE TITLE
反馈：vue/webpack/vue-skeleton-webpack-plugin.md

### ISSUE THREAD

**Issue by xugc** [searchfe/bpwa-tutorial-doc#29] opened 2018-05-15 09:35 UTC
TypeError: Cannot read property 'source' of undefined
    at E:\Visual Studio Code WorkSpace\my-pwa\node_modules\vue-skeleton-webpack-plugin\lib\ssr.js:75:74

**Comment by PengXing** [comment] 2018-05-15 11:20
Duplicate of https://github.com/lavas-project/lavas/issues/160

**Closed as completed by PengXing** 2018-05-15 11:20 UTC
